### ISSUE TITLE
UI Path authentication issue

### ISSUE THREAD

**Issue by nqhoan-axonivy** [axonivy-market/ui-path-connector#23]
Hi Denholm,
I checked and tested around and I also got your issue. It looks like UI Path APi is updated and the code is obsoleted.
Then I must adapt a little bit in code to make it work again.
Could you help to get the attachment in try on your local? then give me the result. Thanks!

Please update your variable also:
```
Variables:
  uiPath-connector:
    organization: 'this-is-new'
    tenant: 'xxxx'
    clientId: 'xxxx'
    userKey: 'xxxxx'
```

What I modified:
The URL looks like missing an org name and tenant name:
![image](https://github.com/axonivy-market/ui-path-connector/assets/83745591/572b8793-0de3-470d-9464-73d2a9b87b8d)

Where we can get 'organization' and 'tenant':
1 is organization
2 is tenant 
![image](https://github.com/axonivy-market/ui-path-connector/assets/83745591/17bae808-a923-4d50-8b46-88d1e9a37cbe)

Must include the organization id in the robot API and Start Job API
![image](https://github.com/axonivy-market/ui-path-connector/assets/83745591/85b5f785-a54f-418c-8887-a4e04d24a192)

Thanks!

FYI @ivy-sgi
